services:
  spdevice-ttyd:
    image: ghcr.io/thin-edge/spdevice-ttyd:latest
    restart: unless-stopped

    # Expose the ttyd port to the host
    ports:
      - "127.0.0.1:7681:7681"

    # Run as a non-root user (UID 1000 is standard for the first host user)
    user: "1000:1000"

    # We strip all kernel capabilities for maximum hardening
    cap_drop:
      - ALL

    environment:
      - SPDEVICE_BROKER=${SPDEVICE_BROKER:-host.containers.internal:1883}

    # required when using docker    
    # extra_hosts:
    #  - "host.containers.internal:host-gateway"
