#!/bin/sh
set -e

case "$1" in
    remove|purge|deconfigure)
        if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
            systemctl stop spdevice || true
            systemctl disable spdevice || true
        fi
        ;;
    upgrade)
        if [ -d /run/systemd/system ] && command -v systemctl >/dev/null 2>&1; then
            systemctl stop spdevice || true
        fi
        ;;
esac
